### ISSUE TITLE
Embedded EJS feature not working

### ISSUE THREAD

**Issue by lmcsu** [windsonR/vite-plugin-virtual-html#36]
Any EJS templates not working because of those tags <%= 
Vite crashes with "Error: Unable to parse HTML; parse5 error code invalid-first-character-of-tag-name"

Vite v4/v5
Node v20

But it works with EJS with the custom render function.

I think there's a problem with the plugins calling order somewhere.
HTML must be rendered before it goes to Vite internal things.

**Comment by windsonR** [comment]
I'll check this in weekend.

**Comment by lmcsu** [comment]
Oh, got it.
I use "type": "module" and there's a silent error in index.mjs that tries to say that __require.resolve is not defined

![image](https://github.com/windsonR/vite-plugin-virtual-html/assets/34189985/2e39cb5b-5116-4962-a51c-6ec86af7d340)

**Comment by windsonR** [comment]
Fixed by 34974c7 ...

**Comment by lmcsu** [comment]
1.1.18 is still not released on NPM, is there something wrong?

**Comment by windsonR** [comment]
My mistake, i commit it but i forgot publish it ..
